### PR TITLE
chore: update escargot

### PR DESCRIPTION
**Pull request by hs0225**
Signed-off-by: Hosung Kim hs852.kim@samsung.com

### CODE REVIEW

**Comment by haesik** [comment]
Will the debugger patch be included?
I mean the issue that every js file have a breakpoint when it used.

**Comment by hs0225** [comment]
@haesik I updated escargot to apply debug patch, but there is a problem that node test fails. I'm now looking for which commit is the problem.

**Comment by haesik** [comment]
@hs0225 I heard that the main branch does not included the patch, can you first talk with @clover2123

**Comment by hs0225** [comment]
@haesik Yes. I'm talking to @clover2123 about this probleam.

**Comment by clover2123** [comment]
IMO this random error is due to the nested finalizer calls in escargot, which creates memory access errors.
The error has been fixed by [escargot #1130](https://github.com/Samsung/escargot/pull/1130)
and I also tested this patch in my repo (https://github.com/clover2123/lwnode/pull/1)

Please rebase Escargot after this patch landed :)

**Comment by hs0225** [comment]
@clover2123 Thanks for the checking the test. I also checked that the latest commit is fine. :smile:

**Comment by haesik** [comment]
@hs0225 is there any problem of latest version of escargot? or is there anything else to update?

**Comment by hs0225** [comment]
@haesik Yes, no more problems in this PR. I finished all the update work. Please review.

**Pull request merged**
