### PR TITLE
chore: update escargot version to release 4.0.0

### PR DESCRIPTION
**Pull request by clover2123**

### CODE REVIEW

**Comment by clover2123** [comment]
@daeyeon @hs0225 Please review this patch.
I updated the version of escargot and fixed some error in github actions.
(we are going to change the WebAssembly engine embedded in escargot in the near future)
But some tests failed. I don't know what to do/fix 😢

**Comment by clover2123** [comment]
I found the main reason of the error and reported an issue (#52)
Sadly, I cannot fix this error right now as explained in #52 (complicated problem)

So, I added the unpassed TC (test/parallel/test-ttywrap-stack.js) to the skip list here
And will fix it in later patch.

**Comment by daeyeon** [comment]
@clover2123 Thanks for the update. We will take a look at the issue updated.

**Review by daeyeon — APPROVED** [review]

**Review by hs0225 — APPROVED** [review]
LGTM

**Pull request merged**
