### PR TITLE
chore: add modules build packages

### PR DESCRIPTION
**Pull request by hs0225**
- To install modules on target, change to sub packages

Signed-off-by: Hosung Kim hs852.kim@samsung.com

### CODE REVIEW

**Review by ryanhc — APPROVED** [review]
:+1:

**Comment by daeyeon** [comment]
It's concerning that the spec description would be again messy from different packages.
What do you think about creating a different spec located in a different directory? 
I just found the gbc `--packaging-dir` option and tested it. It looks to work as expected. 

> --packaging-dir defines the directory for packaging files (default is packaging/). This can be needed if the upstream sources already have a directory named packaging. If you use this option, also define this setting in the package-specific .gbs.conf file (in all relevant branches) so that the remote repository and all other users get the correct setting, too.

https://docs.tizen.org/platform/reference/gbs/gbs-import/

My idea is as below:
1. Move the things related to `modules` to `packaging/modules/modules.spec` or somewhere.
2. For modules, run the gbs build with `--packaging-dir packaging/modules/modules.spec`.

Could you check if this idea makes sense for this case?

**Comment by daeyeon** [comment]
I just found another option. `--spec module.spec` also work. 

Path: `packaging/module.spec`

**Comment by hs0225** [comment]
@daeyeon Oh! good idea. I will try the above method.

**Comment by hs0225** [comment]
@daeyeon I updated my PR. Please check again.

**Review by daeyeon — APPROVED** [review]
:+1:

**Pull request merged**
